  name: Deploy Flask App to Azure

  on:
    push:
      branches:
        - main  # Ejecutar el workflow en cada push a la rama main

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
      # 1. Configurar el repositorio
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Loguearse en Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: industriasecg.azurecr.io  # Cambia al servidor de tu ACR
          username: ${{ secrets.AZURE_ACR_USERNAME }}  # Configura este secreto en GitHub
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      # 3. Construir y empujar la imagen Docker
      - name: Build and push Docker image
        run: |
          docker build -t industriasecg.azurecr.io/flask-app:latest .
          docker push industriasecg.azurecr.io/flask-app:latest

      # 4. Desplegar en Azure Web App for Containers
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ordi  # Cambia al nombre de tu Web App en Azure
          slot-name: production
          images: industriasecg.azurecr.io/flask-app:latest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
